# Generated by Django 4.0.5 on 2022-07-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='payment_max',
            field=models.PositiveIntegerField(verbose_name='Сумма кредита, ДО'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='payment_min',
            field=models.PositiveIntegerField(verbose_name='Сумма кредита, ОТ'),
        ),
    ]
