# Generated by Django 4.0.5 on 2022-07-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_bank_rate_max_alter_bank_rate_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='rate_max',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ставка, ДО'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='rate_min',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ставка, ОТ'),
        ),
    ]
